config/urls.py
# -*- coding: utf-8 -*-
"""Global routings."""
import pathlib

from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.views import defaults as default_views
from django.views.generic import RedirectView
from django.views.i18n import JavaScriptCatalog
from django.views.static import serve
from rest_framework import routers

from www.filestorage.views import StartFileUpload
from www.landing_page.views import LandingPage
from www.tags.views import TagViewset
from www.translated_page.views import PageCatchallView

from discourse_django_sso.views import SSOProviderView


API_ROUTER = routers.DefaultRouter()

API_ROUTER.register('tag/(?P<content_type_id>\d+)', TagViewset)


api_urls = [
    url(r'fileupload/?$', StartFileUpload.as_view(), name="start-file-upload")
]

api_urls += API_ROUTER.urls

urlpatterns = [
    url(r'^$', RedirectView.as_view(pattern_name='landing-discipline'), name='home'),
    url(r'^discipline/?$', LandingPage.as_view()),
    url(r'^discipline(?:/(?P<discipline>[\w+.\-_]+))?/?$', LandingPage.as_view(), name='landing-discipline'),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^jsi18n/$', JavaScriptCatalog.as_view(), name='javascript-catalog'),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, include(admin.site.urls)),

    # User management
    url(r'^users/', include('www.users.urls', namespace='users')),
    url(r'^accounts/', include('allauth.urls')),

    url('^api/', include(api_urls, namespace="api")),

    url(r'^resource/simulation', include('www.simulation.urls', namespace='simulation')),
    url(r'^resource/', include('www.resource.urls', namespace='resource')),
    url(r'^content_item/', include('www.content_item.urls', namespace='content_item')),
    url(r'^course/', include('www.course.urls', namespace='course')),
    url(
        r'^discourse/sso/?',
        SSOProviderView.as_view(
            sso_redirect=settings.DISCOURSE_SSO_URL,
            sso_secret=settings.DISCOURSE_SSO_SECRET,
        ),
        name='sso'
    ),
    url(
        r'^silf/sso/?',
        SSOProviderView.as_view(
            sso_redirect=settings.SILF_SSO_URL,
            sso_secret=settings.SILF_SSO_SECRET,
        ),
        name='silfsso'
    ),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]

    # This only in debug config as in production config we use js reverse rendered to a static file.
    from django_js_reverse.views import urls_js

    favicon_path = pathlib.Path('compose') / 'nginx' / 'www-data' / 'favicon.ico'
    root = pathlib.Path(__file__).parents[1]
    urlpatterns += [
        url(r'^django_js_reverse/?$', urls_js, name='js_reverse'),
        url(r'^favicon.ico/?$', serve, kwargs={"path": str(favicon_path), 'document_root': root})
    ]


urlpatterns += [
    url('(?P<slug>.*)/?', PageCatchallView.as_view())
]

if settings.ENABLE_TOOLBAR:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

www/resource/urls.py
"""Urls for resource app."""
# -*- coding: utf-8 -*-

from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        regex=r'^(?P<pk>\d+)/$',
        view=views.ResourceDetailView.as_view(),
        name='detail'
    ),
    url(
        regex=r'^link/create/(?P<content_item_id>\d+)/?$',
        view=views.LinkResourceCreateView.as_view(),
        name='link-create'
    ),
    url(
        regex=r'^file/create/(?P<content_item_id>\d+)/?$',
        view=views.FileResourceCreateView.as_view(),
        name='file-create'
    ),
    url(
        regex=r'^document/create/(?P<content_item_id>\d+)/?$',
        view=views.DocumentResourceCreateView.as_view(),
        name='document-create'
    ),
    url(
        regex=r'^document/edit/(?P<pk>\d+)/?$',
        view=views.DocumentResourceUpdateView.as_view(),
        name='document-edit-metadata'
    ),
    url(
        regex=r'^file/upload/(?P<pk>\d+)/?$',
        view=views.FileResourceUploadView.as_view(),
        name='file-upload'
    ),
    url(
        regex=r'^link/edit/(?P<pk>\d+)/?$',
        view=views.LinkResourceUpdateView.as_view(),
        name='link-edit'
    ),

    url(
        regex=r'^file/edit/(?P<pk>\d+)/?$',
        view=views.FileResourceUpdateView.as_view(),
        name='file-edit'
    ),
    url(
        regex=r'^link/delete/(?P<pk>\d+)/?$',
        view=views.ResourceDeleteView.as_view(),
        name='delete'
    ),
    url(
        regex=r'^document/upload/(?P<pk>\d+)/?$',
        view=views.DocumentResourceEditMarkdownView.as_view(),
        name='document-upload'
    ),
    url(
        regex=r'^video/create/(?P<content_item_id>\d+)/?$',
        view=views.VideoResourceCreateView.as_view(),
        name='video-create'
    ),
    url(
        regex=r'^video/upload/(?P<pk>\d+)/?$',
        view=views.VideoResourceUpdateUrl.as_view(),
        name='video-upload'
    ),
    url(
        regex=r'^video/edit/(?P<pk>\d+)/?$',
        view=views.VideoResourceUpdateView.as_view(),
        name='video-edit'
    ),
    url(
        regex=r'^subtitle/create/(?P<content_item_id>\d+)/?$',
        view=views.SubtitleResourceCreateView.as_view(),
        name='subtitle-create'
    ),
    url(
        regex=r'^subtitle/upload/(?P<pk>\d+)/?$',
        view=views.SubtitleResourceUpdateUrl.as_view(),
        name='subtitle-upload'
    ),
    url(
        regex=r'^subtitle/edit/(?P<pk>\d+)/?$',
        view=views.SubtitleResourceUpdateView.as_view(),
        name='subtitle-edit'
    ),
]

www/users/urls.py
"""URLs for users app."""
# -*- coding: utf-8 -*-

from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    # URL pattern for the UserListView
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),

    # URL pattern for the UserRedirectView
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),

    # URL pattern for the UserDetailView
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),

    # URL pattern for the UserUpdateView
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
]

www/resource/models.py
# -*- coding: utf-8 -*-
"""Models for resource app."""

import io
from pathlib import Path

import slugify
from django.core.exceptions import ValidationError
from django.core.files.storage import default_storage
from django.core.validators import URLValidator
from django.db import models
from django.db.models.signals import post_save
from django.dispatch.dispatcher import receiver
from django.utils import timezone
from django.utils.translation import ugettext_lazy

from www.content_item.const import ResourceType, License, LANGUAGES
from www.content_item.models import validate_language_code

from .convert_tasks import convert_document_resource


def read_restricted_domains():
    """ Read file with restricted domains to list  """
    restricted_domain_file = Path(__file__).parent / 'data' / 'restricted_domains.list'
    with restricted_domain_file.open() as domain_file:  # pylint: disable=no-member
        domains = domain_file.readlines()
    return [d.strip() for d in domains]


restricted_domains = read_restricted_domains()


def validate_link_url(url):
    """Validate link resource."""
    url_valid = URLValidator()
    url_valid(url)
    for d in restricted_domains:
        if url.startswith('http://' + d) or url.startswith('https://' + d):
            raise ValidationError('Restricted domain')


class ResourceRole(models.Model):
    """Resource role model."""

    slug = models.SlugField()
    name = models.CharField(max_length=1000)

    def __str__(self):
        return self.name


class Resource(models.Model):
    """Resource model."""

    content_item = models.ForeignKey(
        "content_item.ContentItem",
        null=False,
        related_name="resources"
    )

    resource_type = models.CharField(
        verbose_name=ugettext_lazy('Resource type'),
        help_text=ugettext_lazy('Type of the resource'),
        max_length=100,
        choices=ResourceType.choices,
        validators=[ResourceType.validator],
        default=ResourceType.link
    )

    resource_license = models.CharField(
        verbose_name=ugettext_lazy('Resource license'),
        help_text=ugettext_lazy('License on which resource is published'),
        max_length=12,
        choices=License.choices,
        validators=[License.validator],
        default=License.cc_by
    )

    title = models.CharField(
        verbose_name=ugettext_lazy('Resource title'),
        help_text=ugettext_lazy('Short title of the resource'),
        null=False, blank=False,
        max_length=256
    )

    description = models.TextField(
        verbose_name=ugettext_lazy('Resource description'),
        null=True, blank=True
    )

    role = models.ForeignKey(ResourceRole, null=True)

    default = models.BooleanField(
        verbose_name=ugettext_lazy('Is default?'),
        null=False, blank=False, default=False
    )

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):

        from www.content_item.models import ContentItem
        ContentItem.objects.filter(pk=self.content_item_id).update(
            last_updated_at=timezone.now()
        )

        self.__ensure_default_constraints()

        super().save(force_insert, force_update, using, update_fields)

    def __ensure_default_constraints(self):
        if self.default:
            self.content_item.resources.exclude(  # pylint: disable=no-member
                pk=self.pk).filter(default=True).update(default=False)
        elif self.content_item.resources.exclude(pk=self.pk).count() == 0:  # pylint: disable=no-member
            self.default = True

    class Meta:
        # Right now just make ordering consistent
        ordering = ['-default', 'pk']


class LinkResource(Resource):
    """ Resource of link type - url to anything in the web """

    url = models.TextField(
        verbose_name=ugettext_lazy('Link url'),
        null=False, blank=False,
        validators=[validate_link_url],
    )


class FileResource(Resource):
    """File resource."""

    path = models.TextField(
        verbose_name=ugettext_lazy('File path'),
        null=True, blank=True
    )

    @property
    def download_url(self):
        """Http url for file download."""
        if self.path is None:
            return None
        return default_storage.base_url + self.path

    @property
    def is_complete(self):
        """Check if file resource is complete (has non null attached file path)"""
        return self.path is not None


def read_example_document() -> str:
    """Returns example document."""
    example_resource = Path(__file__).parent / 'data' / 'example_document_resource.md'
    return example_resource.read_text()  # pylint: disable=no-member


class DocumentResource(Resource):
    """Resource containing a document."""

    HTML_MIMETYPE = "text/html"  # pragma: no cover
    ODT_MIMETYPE = "application/vnd.oasis.opendocument.text"  # pragma: no cover
    DOCX_MIMETYPE = "application/vnd.openxmlformats-officedocument.wordprocessingml.document"  # pragma: no cover
    PDF_MIMETYPE = "application/pdf"  # pragma: no cover

    markdown = models.TextField(
        verbose_name=ugettext_lazy("Markdown"),
        null=True, blank=True,
        default=None,
    )

    @property
    def defaulted_markdown(self) -> str:
        """
        Returns document markdown. If markdown is None return
        default markdown without changing the model.
        """
        if self.markdown is None:
            return read_example_document()
        return self.markdown

    @property
    def is_complete(self):
        """Check if resource is complete (has markdown)"""
        return self.markdown is not None

    def _store_resource(self, file_name: str, contents: bytes) -> str:  # pragma: no cover
        name = "{s.content_item.pk}/{s.pk}/{name}".format(  # pylint: disable=missing-format-attribute
            s=self, name=file_name
        )
        return default_storage.save(name, io.BytesIO(contents))

    def store_resource(self, file_name: str, mimetype: str, contents: bytes):  # pragma: no cover
        """
        Stores resource derivative.

        :param contents: Computed derivative contents.
        :param mimetype: Mimetype for the derivative.
        :param file_name: File name to store.
        """
        derivative, created = DocumentResourceDerivative.objects.get_or_create(
            resource=self,
            mime_type=mimetype
        )
        if not created and derivative.path is not None:
            default_storage.delete(derivative.path)
        derivative.path = self._store_resource(file_name, contents)
        derivative.is_ready = True
        derivative.save()


@receiver(post_save, sender=DocumentResource)
def render_derivatives(instance: DocumentResource, **kwargs):  # pylint: disable=unused-argument
    """Renders markdown to different formats on save."""

    if instance.markdown is None:
        return

    base_filename = slugify.slugify_filename(instance.title)
    convert_document_resource.delay(instance.id, base_filename)


class DocumentResourceDerivative(models.Model):
    """
    Stores resource derivative --- a transformed version of document resource.
    """

    resource = models.ForeignKey(
        DocumentResource, null=False, blank=False,
        related_name="derivatives"
    )
    mime_type = models.CharField(
        max_length=128, null=False
    )
    path = models.CharField(default=None, null=True, max_length=1024)
    is_ready = models.BooleanField(default=False)
    celery_task_id = models.CharField(max_length=128, null=True, blank=True)

    @property
    def download_url(self):  # pragma: no cover
        """Http url for file download."""
        if self.path is None:
            return None
        return default_storage.base_url + self.path

    class Meta:
        unique_together = (
            ("resource", "mime_type"),
        )


class VideoResource(FileResource):
    """ Video resource - it is uploaded to swift and to youtube """

    youtube_id = models.TextField(
        verbose_name=ugettext_lazy('Youtube video id'),
        null=True, blank=True
    )


class SubtitleResource(FileResource):
    """ Subtitle resource - this are subtitles for video resource """

    language = models.CharField(
        verbose_name=ugettext_lazy('Resource language'),
        max_length=2,
        validators=[validate_language_code],
        choices=LANGUAGES
    )

    subtitle_id = models.TextField(
        verbose_name=ugettext_lazy('Subtitle id'),
        help_text=ugettext_lazy(
            'Id of subtitle generated by YouTube when adding to video'
        ),
        null=True, blank=True
    )

www/resource/templates/resource/document_resource_add_form.html
{% extends "resource/resource_form.html" %}

{% load i18n %}

{% block form-description %}
    {% blocktrans %}
        Here you will fill only metadata for the form. Actual HTML file you will be added (or edited)
        after you click submit.
    {% endblocktrans %}
{% endblock %}

{% block form-scripts %}
    {% include "resource/partials/html_resource_scripts.html" %}
{% endblock %}

www/resource/templates/resource/file_resource_upload_form.html
{% load bootstrap3 i18n static %}

<div class="container-fluid">
  <div class="row">
    <div class="col-xs-12">
      <div id="upload-messages">
      <div class="alert alert-info" role="alert">
        {% trans "Please select file below and then click 'Submit' " %}
      </div>
      </div>
    </div>
  </div>
</div>

<form id="resource-form" class="form-horizontal" method="post">
  {% bootstrap_form form %}

  <div class="container-fluid">
    <div class="row">
      <div class="col-xs-12 mt-1">
        <input name="file" type="file" id="id_file">
      </div>
    </div>
  </div>
  <div class="container-fluid">
    <div class="row">
      <div class="col-xs-12 mt-1">
      <button id="upload-button" class="btn btn-danger" data-toggle="tooltip" disabled>
        <i class="fa fa-cloud-upload" aria-hidden="true"></i> {% trans "Submit" %}
      </button>
        </div>
    </div>
  </div>

  <div class="container-fluid">
    <div class="col-xs-12">
      <div id="upload-progress" class="row progress">
        <div class="progress-bar bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100">
        </div>
      </div>
    </div>
  </div>

</form>

{#<script src="{% static "js/resources/resources.js" %}"></script>#}

<script>
    (function () {
        var manager = new FileResourceManager("{{ action }}", "{{ content_item.title|slugify }}");
    })();
</script>

www/resource/templates/resource/html_resource_file_form.html
{% extends "resource/resource_form.html" %}

{% load i18n %}

{% block form-description%}
    <p>
        {% blocktrans %}
      Write your document in the editor below.
    {% endblocktrans %}
    <a href="{% url "resource:document-upload" pk=object.pk%}">Click here for distraction-free mode. </a>
    </p>
{% endblock %}

{% block form-scripts %}
    {% include "resource/partials/html_resource_scripts.html" %}
{% endblock %}

www/resource/templates/resource/html_resource_file_form_full.html
{% extends "base.html" %}

{% load i18n %}

{% block content %}
    <form method="POST" accept-charset="UTF-8">
    {% csrf_token %}
        <h1>
            <label for="id_markdown">
                {{ object.title }}
            </label>
        </h1>
        <textarea id="id_markdown" name="markdown"></textarea>
        <button class="btn btn-primary"><i class="fa fa-cloud-upload"></i>{% trans "Save and return to content item" %} </button>
    </form>
{% endblock content %}

{% block page_js %}
    {% include "resource/partials/html_resource_scripts.html" %}
{% endblock %}

www/resource/templates/resource/resource_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}Resource: {{ object.pk }}{% endblock %}

{% block content %}
<div class="container">

  <div class="row">
    <div class="col-sm-12">

      <h2>{{ object.pk }}</h2>
      {% if object.description %}
        <p>description: {{ object.description }}</p>
      {% endif %}

        <p>type: {{ object.resource_type }}</p>
        <p>license: {{ object.resource_license }}</p>
        <p>language: {{ object.language }}</p>
        {% if object.role %}
          <p>role: {{ object.role.name }}</p>
        {% endif %}
        <p>default: {{ object.default }}</p>
    </div>
  </div>

<!-- Action buttons -->
<div class="row">

  <div class="col-sm-12">
    <a class="btn btn-primary" href="{% url 'resource:update' pk=object.pk %}" role="button">Modify</a>
  </div>

</div>
<!-- End Action buttons -->

</div>
{% endblock content %}

www/resource/templates/resource/resource_form.html
{% load crispy_forms_tags static %}

<div id="form-messages">
  {# Now empty, will be populated by JS if any messages need to be presented to the user #}
</div>

{% block form-description %} {% endblock %}

<form
  id="resource-form" class="form-horizontal" method="post" action="{{ action }}"
  accept-charset="UTF-8"
>
  {% csrf_token %}
  {{ form|crispy }}
</form>

{% block form-scripts %}

{% endblock %}

www/resource/templates/resource/resource_list.html
{% extends "base.html" %}
{% load static i18n %}
{% block title %}Members{% endblock %}

{% block content %}

<div class="container">
  <h2>resource</h2>
  <div class="list-group">
    {% if resource_list %}
        {% for resource in resource_list %}
            <a href="{% url 'resource:detail' resource.id %}" class="list-group-item">
                <h4 class="list-group-item-heading">
                    {{ resource.description }}
                    {% if resource.default %}
                    <i class="fa fa-star" aria-hidden="true" title="{% trans "default" %}"></i>
                    {% endif %}
                </h4>
            </a>
        {% endfor %}
    {% else %}
        <p>No resource.</p>
    {% endif %}
  </div>
</div>
{% endblock content %}