config/urls.py
# -*- coding: utf-8 -*-
"""Global routings."""
import pathlib

from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.views import defaults as default_views
from django.views.generic import RedirectView
from django.views.i18n import JavaScriptCatalog
from django.views.static import serve
from rest_framework import routers

from www.filestorage.views import StartFileUpload
from www.landing_page.views import LandingPage
from www.tags.views import TagViewset
from www.translated_page.views import PageCatchallView

from discourse_django_sso.views import SSOProviderView


API_ROUTER = routers.DefaultRouter()

API_ROUTER.register('tag/(?P<content_type_id>\d+)', TagViewset)


api_urls = [
    url(r'fileupload/?$', StartFileUpload.as_view(), name="start-file-upload")
]

api_urls += API_ROUTER.urls

urlpatterns = [
    url(r'^$', RedirectView.as_view(pattern_name='landing-discipline'), name='home'),
    url(r'^discipline/?$', LandingPage.as_view()),
    url(r'^discipline(?:/(?P<discipline>[\w+.\-_]+))?/?$', LandingPage.as_view(), name='landing-discipline'),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^jsi18n/$', JavaScriptCatalog.as_view(), name='javascript-catalog'),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, include(admin.site.urls)),

    # User management
    url(r'^users/', include('www.users.urls', namespace='users')),
    url(r'^accounts/', include('allauth.urls')),

    url('^api/', include(api_urls, namespace="api")),

    url(r'^resource/simulation', include('www.simulation.urls', namespace='simulation')),
    url(r'^resource/', include('www.resource.urls', namespace='resource')),
    url(r'^content_item/', include('www.content_item.urls', namespace='content_item')),
    url(r'^course/', include('www.course.urls', namespace='course')),
    url(
        r'^discourse/sso/?',
        SSOProviderView.as_view(
            sso_redirect=settings.DISCOURSE_SSO_URL,
            sso_secret=settings.DISCOURSE_SSO_SECRET,
        ),
        name='sso'
    ),
    url(
        r'^silf/sso/?',
        SSOProviderView.as_view(
            sso_redirect=settings.SILF_SSO_URL,
            sso_secret=settings.SILF_SSO_SECRET,
        ),
        name='silfsso'
    ),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]

    # This only in debug config as in production config we use js reverse rendered to a static file.
    from django_js_reverse.views import urls_js

    favicon_path = pathlib.Path('compose') / 'nginx' / 'www-data' / 'favicon.ico'
    root = pathlib.Path(__file__).parents[1]
    urlpatterns += [
        url(r'^django_js_reverse/?$', urls_js, name='js_reverse'),
        url(r'^favicon.ico/?$', serve, kwargs={"path": str(favicon_path), 'document_root': root})
    ]


urlpatterns += [
    url('(?P<slug>.*)/?', PageCatchallView.as_view())
]

if settings.ENABLE_TOOLBAR:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

www/content_item/urls.py
"""Urls for resource app."""
# -*- coding: utf-8 -*-

from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        regex=r'add(?:/(?P<group_id>\d+))?/?$',
        view=views.ContentItemCreate.as_view(),
        name='add-lang'
    ),
    url(
        regex=r'add/?$',
        view=views.ContentItemCreate.as_view(),
        name='add'
    ),
    url(
        regex=r'^edit/(?P<pk>\d+)/?$',
        view=views.ContentItemUpdate.as_view(),
        name='edit'
    ),
    url(
        regex=r'^verify/(?P<pk>\d+)/?$',
        view=views.ContentItemVerifyView.as_view(),
        name='verify'
    ),
    url(
        regex=r'detail/(?P<pk>\d+)/?$',
        view=views.ContentItemDisplay.as_view(),
        name='detail'
    ),
    url(
        regex=r'detail/resources/(?P<content_id>\d+)/?$',
        view=views.get_content_resources,
        name='contentresources'
    ),
    url(
        r'search/advanced/?$',
        view=views.AdvancedContentItemSearchView.as_view(),
        name='search-advanced'
    ),
    url(
        r'search(?:/domain/(?P<domain>[\w\-_\+\d]+))?(?:/page/(?P<page>\d+))?'
        r'(?:/methodology/(?P<methodology>[\w\-_\+\d]+))?(?:/term/(?P<term>.*))?/?',
        view=views.ContentItemSearchView.as_view(),
        name='search'
    ),
    url(
        regex=r'domain_description_edit/(?P<pk>\d+)/?$',
        view=views.ContentItemEditDomainDescription.as_view(),
        name='domain_description_edit'
    ),
    url(
        regex=r'domain_description_add/(?P<domain>\d+)/(?P<content_item>\d+)/?$',
        view=views.ContentItemAddDomainDescription.as_view(),
        name='domain_description_add'
    ),
    url(
        r'delete/(?P<pk>\d+)',
        view=views.ContentItemDeleteView.as_view(),
        name="delete"
    )

]

www/content_item/models.py
# -*- coding: utf-8 -*-
"""Models for ContentItem app"""
import typing
from collections import OrderedDict

import markdown
from django.conf import settings
from django.contrib.postgres.fields import ArrayField
from django.core.exceptions import ValidationError
from django.db import models
from django.utils.translation import ugettext_lazy
from djchoices import ChoiceItem, DjangoChoices

from www.content_item import const
from www.resource.models import License
from www.utils.bleach import CLEANER
from www.utils.validators import (
    image_name_validator,
    validate_language_code
)


class DomainType(models.Model):
    """
    DomainType model.

    Represents (unsurprisingly) type of domain, that is a type of classifier that can be attached
    to ContentItem. Example of DomainType would be age-group.

    List of default domains is in ``migrations/domains.yml.``
    """

    slug = models.SlugField(unique=True)
    name = models.CharField(max_length=1000)
    order = models.IntegerField(null=True, default=None)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['order', 'slug']


class Domain(models.Model):

    """
    DomainType model.

    Represents (unsurprisingly) a domain, that is a classifier that can be attached
    to ContentItem. Example of Domain would be `9-12 years` (for domain type `age group`)
    List of default domains is in ``migrations/domains.yml.``
    """

    # flake whines about shadowing builtin here, however this name is reasonable
    type = models.ForeignKey(DomainType, related_name="domains")  # noqa: B001
    slug = models.SlugField(unique=True)
    name = models.CharField(max_length=1000)
    order = models.IntegerField(null=True, default=None)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['type__order', 'type__slug', 'order', 'slug']


class ContentItemLanguageGroup(models.Model):
    """
    Content Item group, content items with the same group have same content but in different languages
    """
    pass


class ContentItem(models.Model):
    """
    Content item model.

    For information on how Content Items are indexed see search_indexes.ContentIndex.
    """

    class ContentItemType(DjangoChoices):
        """
        Types of Content item.
        """

        basic = ChoiceItem('basic', label=ugettext_lazy('Basic'))
        movie = ChoiceItem('movie', label=ugettext_lazy('Movie'))

    title = models.CharField(
        max_length=100,
        verbose_name=ugettext_lazy("Title"),
        help_text=ugettext_lazy(
            "Provide concise descriptive title for your content. It should be short "
            "yet convey what your content is. "),
        blank=False,
        null=False
    )

    description = models.TextField(
        verbose_name=ugettext_lazy("Description"),
        null=True, blank=True,
        help_text=ugettext_lazy(
            "Optional description for your content. Markdown formatting allowed."
        )
    )

    authors = ArrayField(
        base_field=models.CharField(max_length=128),
        verbose_name=ugettext_lazy("Authors"),
        null=False,
        help_text=ugettext_lazy(
            "Provide list of authors. "
            "To add a new author write their name and press enter or comma. "
        )
    )

    owners = models.ManyToManyField(
        to=settings.AUTH_USER_MODEL,
        verbose_name=ugettext_lazy("Owners"),
        help_text=ugettext_lazy("List of users that can edit this resource")
    )

    # flake whines about shadowing builtin here, however this name is reasonable
    type = models.CharField(  # noqa: B001
        verbose_name=ugettext_lazy('Type'),
        help_text=ugettext_lazy(
            'Type of the this content item, it cannot be changed.'
        ),
        max_length=100,
        choices=ContentItemType.choices,
        validators=[ContentItemType.validator],
        default=ContentItemType.basic
    )

    tags = models.ManyToManyField(
        to="tags.Tag",
        db_index=True,
        blank=True,
        verbose_name=ugettext_lazy("Tags"),
        help_text=ugettext_lazy(
            "Tags help others find your contents. "
            "To add a new tag write its name and press enter or comma. ")

    )

    domains = models.ManyToManyField(
        to=Domain,
        verbose_name=ugettext_lazy("Domains"),
        blank=True,
        help_text=ugettext_lazy(
            "You can select more than one domain by Ctrl clicking on domains (On mac use Command '⌘' + Click)."
        )
    )

    main_discipline = models.ForeignKey(
        Domain,
        null=False,
        blank=False,
        related_name="+",
        limit_choices_to={
            "type__slug": "discipline"
        },
        help_text=ugettext_lazy("Main discipline, you can select more disciplines below.")

    )

    # flake whines about shadowing builtin here, however this name is reasonable
    license = models.CharField(  # noqa: B001
        verbose_name=ugettext_lazy('Resource license'),
        help_text=ugettext_lazy(
            'License on which resource is published. '
            'By selecting this license you certify that you have right to release '
            'this content under this license. '
            'Please note that while '
            'GUI will enable you to change the license, taking away rights '
            'from users retroactively is not possible in EC legal system '
            '(also this is not a legal advice, seek legal counsel if you need it).'
        ),
        max_length=128,
        choices=License.choices,
        validators=[License.validator],
        default=License.cc_by
    )

    cover_image = models.ImageField(
        verbose_name=ugettext_lazy('Cover image for this resource'),
        blank=True, null=True,
        validators=[image_name_validator],
        help_text=ugettext_lazy('Will be cropped to aspect ratio 6.75:1 (or 1080x160px)')
    )

    cover_image_resized = models.ImageField(
        verbose_name=ugettext_lazy('Cover image for this resource, resized to correct aspect ratio of 6.75:1'),
        blank=True, null=True
    )

    miniature_image = models.ImageField(
        verbose_name=ugettext_lazy('Miniature image for this resource'),
        help_text=ugettext_lazy(
            'Miniature image will be auto generated from Cover image if left blank or deleted. '
            'If you upload please use file with 1.185:1 aspect ratio (or 154x130px)'
        ),
        blank=True, null=True,
        validators=[image_name_validator]
    )

    miniature_image_resized = models.ImageField(
        verbose_name=ugettext_lazy('Miniature image for this resource, resized to correct aspect ratio of 1.185:1'),
        blank=True, null=True
    )

    min_group_size = models.PositiveIntegerField(
        verbose_name=ugettext_lazy('Minimal participant group size'),
        null=True, blank=True
    )
    max_group_size = models.PositiveIntegerField(
        verbose_name=ugettext_lazy('Maximal participant group size'),
        null=True, blank=True
    )
    activity_length = models.PositiveIntegerField(
        verbose_name=ugettext_lazy('Length of activity (minutes)'),
        null=True, blank=True
    )
    staff = models.PositiveIntegerField(
        verbose_name=ugettext_lazy('Number of staff'),
        null=True, blank=True
    )
    technical_requirements = models.TextField(
        verbose_name=ugettext_lazy("Special technical requirements"),
        null=True, blank=True
    )
    knowledge_gain = models.TextField(
        verbose_name=ugettext_lazy("Knowledge acquisition gain"),
        null=True, blank=True
    )

    created_at = models.DateTimeField(
        auto_now_add=True
    )

    last_updated_at = models.DateTimeField(
        auto_now=True, editable=False, null=False
    )

    hidden = models.BooleanField(
        default=False
    )
    """
    If this is set to true model is considered deleted, and will be removed from indexes and hence not-searchable. 
    """

    group = models.ForeignKey(ContentItemLanguageGroup)

    language = models.CharField(
        verbose_name=ugettext_lazy('Resource language'),
        max_length=2,
        validators=[validate_language_code],
        default='en',
        choices=const.LANGUAGES
    )

    featured = models.BooleanField(
        default=False,
        verbose_name=ugettext_lazy("Featured"),
        help_text=ugettext_lazy("Check this if you want to have this item to be featured on main page")
    )

    workforce_description = models.TextField(
        default='',
        blank=True,
        null=False,
        verbose_name=ugettext_lazy("Workforce description"),
        help_text=ugettext_lazy(
            "Here you can describe how this content will help students obtain "
            "high standing among workforce. If provided it will **replace** "
            "generic workforce box that contains discipline specific messages "
            "provided bu the consortium. You may use markdown here"
        )
    )

    workforce_title = models.CharField(
        default='',
        null=False,
        blank=True,
        max_length=1024,
        verbose_name=ugettext_lazy("Workforce description label"),
        help_text=ugettext_lazy(
            "If 'Workforce description' is filled this enables you to override "
            "it's title. "
        )
    )

    verified = models.BooleanField(
        default=False,
        verbose_name=ugettext_lazy("Is verified"),
        help_text=ugettext_lazy("Check if content is verified or partner provided.")
    )

    @property
    def workforce_description_html(self):
        """
        HTML formatted workforce description, it overrides generic
        description block.
        """
        return CLEANER.clean(markdown.markdown(self.workforce_description))

    @property
    def description_html(self):  # pragma: no cover
        """
        HTML formatted description.
        """

www/content_item/templates/content_item/advanced_search.html
{% extends "base.html" %}

{% load i18n bootstrap3 %}

{% block page-css %}
  <style>
    .control-label {
      font-weight: bold;
    }
  </style>
{% endblock %}

{% block content %}
  <p>
    {% blocktrans %}

    {% endblocktrans %}
  </p>
  <h3>{% trans "Search parameters" %}</h3>
  <form id="search_form" method="POST">
    {% csrf_token %}
    <div class="container">
      <div class="row">
        {% for field in form %}
          {% if field.name == 'q' %}
            <div class="col-12">
              {% bootstrap_field field %}
            </div>
          {% elif field.name == 'license' or field.name == 'language' or field.name == 'rri'  %}
            <div class="col-md-6 col-xs-12">
              {% bootstrap_field field %}
            </div>
          {% else %}
            <div class="col-xl-3 col-lg-4 col-sm-6">
              {% bootstrap_field field %}
            </div>
          {% endif %}
        {% endfor %}
      </div>
      <div class="row">
        <button class="btn-primary btn">{% trans "Search" %}</button>
      </div>
    </div>



    <h3 class="mt-4 mb-4">{% trans "Search Results" %}</h3>


    {% include "content_item/fragments/content_item_search_result.html" %}

    <div>
      <button
        class="btn btn-primary"
        {% if page_obj.has_previous %}name="page" value="{{ page_obj.previous_page_number }}"
        {% else %}disabled{% endif %}
      >
        <i class="fa fa-arrow-circle-left" aria-hidden="true"></i> {% trans "Previous results" %}
      </button>
      <button
        class="btn btn-primary float-md-right"
        {% if page_obj.has_next %}name="page" value="{{ page_obj.next_page_number }}"
        {% else %}disabled{% endif %}
      >
        {% trans "Next results" %} <i class="fa fa-arrow-circle-right" aria-hidden="true"></i>
      </button>
    </div>
  </form>
{% endblock %}

{% block page_js %}
  <script type="application/javascript">
    var form = new FormWithTags("#search-submit",
      [{"selector": "#id_tags"}]
    );
    $('#id_domain').change(function(){
      $('#search_form').submit();
    });
    $('#id_language').change(function(){
      $('#search_form').submit();
    });
  </script>

{% endblock %}

www/content_item/templates/content_item/content_item_display.html
{% extends "base.html" %}

{% load bootstrap3 i18n static page_block %}

{% block title %}{{ object.title }}{% endblock title %}

{% block page_js %}
  <script>
      window.content_item_id = "{{ object.pk }}";
      window.content_item_resources_url = "{% url 'content_item:contentresources' object.pk %}";
      {% if DISCOURSE_ROOT_URL and ENABLE_DISCOURSE_FORUM_TRIGGERS %}
          window.DiscourseEmbed = {
              discourseUrl: '{{ DISCOURSE_ROOT_URL }}',
              discourseEmbedUrl: '{{ request.build_absolute_uri }}'
          };
      {% endif %}
  </script>
  {% if DISCOURSE_ROOT_URL and ENABLE_DISCOURSE_FORUM_TRIGGERS %}
    <script src="{{ DISCOURSE_ROOT_URL }}javascripts/embed.js"></script>
  {% endif %}
  <script src="{% static "content-item/content_item.js" %}"></script>
{% endblock %}

{% block page-css %}

{% endblock page-css %}

{% block content %}
  <div class="container-fluid">
    {% if object.cover_image_resized %}
      <div class="row">
        <div class="col">
          <img src="{{ object.cover_image_resized.url }}" class="cover-image">
        </div>
      </div>
    {% elif object.cover_image %}
      <div class="row">
        <div class="col">
          <img src="{{ object.cover_image.url }}" class="cover-image">
        </div>
      </div>
    {% endif %}
  </div>

  <div class="container {{ object.main_discipline.slug }}">
    <div class="row">
      <!-- no idea where I should put this one small>{{ object.type }}</small -->
      <div class="col-xs-12 col-sm-8 col-lg-10 content-item-title">
          <span class="discourse-embed">
            {{ object.title }}
          </span>
        <a href="{{ license.url }}">
          <img class="ci-license" src="{% static license.icon %}" alt="{{ license.label }}">
        </a>
      </div>
      <div class="col-xs-12 col-sm-4 col-lg-2 content-item-rating">
        {% if object.verified %}
          <span class="ci-verified" data-toggle="tooltip" data-placement="left"
                title="{% trans "This content was verified by the consortium." %}">
            {% trans "Verified" %} <i class="fa fa-question-circle-o"></i> </span>
        {% else %}
          <span class="ci-unverified"  data-toggle="tooltip" data-placement="left"
          title="{% trans "This content has not been yet verified by project consortium, please check it with extra care." %}">{% trans "Unverified" %} <i class="fa fa-question-circle-o"></i></span>
        {% endif %}
        {% if perms.content_item.can_verify %}
          <button
            id="update-verified"
            href="{% url "content_item:verify" pk=object.pk %}"
            class="btn btn-primary btn-sm">{% trans "Update" %}</button>
        {% endif %}
      </div>
    </div>

    <div class="row">
      <div class="col-sm-8 col-lg-10 content-item-authors">
        <strong>{% trans "Authors" %}:</strong> {% for author in object.authors %}
        {{ author }}{% if not forloop.last %},{% endif %} {{ endif }}{% endfor %}
      </div>
      <div class="col-sm-4 col-lg-2 content-item-field text-center">
        {% trans object.main_discipline.name %}
      </div>
    </div>

    <div class="row">
      <div class="col-md-4">{% trans "This content is provided in languages" %}:</div>
      {% for c in object.group.contentitem_set.all %}
        <div class="ml-3">
          <a href="{% url "content_item:detail" pk=c.pk %}"
             class="{% if c.language == object.language %}
                      content-item-language-link-active
                    {% else %}
                      content-item-language-link
                    {% endif %}">
            {{ c.language_name }}
          </a>
        </div>
      {% endfor %}
    </div>

    <div class="row">
      <div class="col">
        <hr class="content-item-titleseparator"/>
      </div>
    </div>

    <div class="row">
      <div class="invisible col-md-8"> [this block with combo boxes and tags placeholder]</div>

    </div>

    <div class="row content-item-padded-row-top">
      <div class="col-xs-12 col-lg-8">
        <div class="content-item-description discourse-embed">
          {{ object.description_html|safe }}
        </div>
        {% if object.technical_requirements %}
           <div class="content-item-padded-row-top">
             <div class="content-item-tagstitle">{% trans "Technical requirements" %}</div>
             &emsp; {{ object.technical_requirements }} <br>
           </div>
        {% endif %}

        {% if object.knowledge_gain %}
          <div class="content-item-padded-row-top content-item-padded-row-bottom">
            <div class="content-item-tagstitle">{% trans "Knowledge acquisition gain" %}</div>
            &emsp; {{ object.knowledge_gain }} <br>
          </div>
        {% endif %}
        {% if not object.workforce_description %}
          {% page_block workforce_block language=object.language %}
        {% else %}
          <div class="card mb-3">
          <h4 class="card-header">
            {% if object.workforce_title %}{{ object.workforce_title }}
            {% else %}{% trans "Workforce description" %}{% endif %}</h4>
          <div class="card-body">
            {{ object.workforce_description_html|safe }}
          </div>
      </div>
        {% endif %}

        <div id="rri-methodologies" role="tablist" aria-multiselectable="true">

          {% if rri %}
            <div class="card">
              <div class="card-header" role="tab" id="rri">
                <div class="content-item-tagstitle">
                  <a id= "rri-link" class="collapsed" data-toggle="collapse" data-parent="#rri-methodologies" href="#rri-desc" aria-expanded="false" aria-controls="rri-desc">
                    Responsible Research and Innovation
                  </a>
                </div>
              </div>

              <div id="rri-desc" class="collapse" role="tabcard" aria-labelledby="rri">
                <div class="card-body container">
                  {% for domain, desc in rri.items %}
                    <div class="row">
                      <div class="col">
                        &emsp;<a class="search-link" href="{% url "content_item:search" domain=domain.slug %}">{% trans domain.name %}</a>
                      </div>
                    </div>
                    {% include "content_item/fragments/content_item_domain_descriptions.html" with object=object domain=domain desc=desc %}
                  {% endfor %}
                </div>
              </div>
            </div>
          {% endif %}

          {% if methodologies %}
            <div class="card">
              <div class="card-header" role="tab" id="methodologies">
                <div class="content-item-tagstitle">
                  <a class="collapsed" data-toggle="collapse" data-parent="#rri-methodologies" href="#methodologies-desc" aria-expanded="false" aria-controls="methodologies-desc">
                    Learning Methodologies
                  </a>
                </div>
              </div>
              <div id="methodologies-desc" class="collapse" role="tabcard" aria-labelledby="methodologies">
                <div class="card-body">
                  {% for domain, desc in methodologies.items %}
                    <div class="row">
                      <div class="col">
                        <a class="search-link" href="{% url "content_item:search" domain=domain.slug %}">{% trans domain.name %}</a>
                        {% page_block domain.slug language=object.language template="content_item/fragments/content_item_domain_popover.html" %}
                      </div>
                    </div>
                    {% include "content_item/fragments/content_item_domain_descriptions.html" with object=object domain=domain desc=desc %}
                  {% endfor %}
                </div>
              </div>
            </div>
          {% endif %}

        </div>
      </div>

      <div class="col-xs-12 col-lg-4 content-item-infoblock">
        <div class="col-md-12">
          {% if object.min_group_size is not None or object.max_group_size is not None %}
            <div class="content-item-tagstitle">{% trans "Group" %}</div>
            &emsp;
            {% if object.min_group_size is not None and object.max_group_size is None %}
              >{{ object.min_group_size }}
            {% endif %}
            {% if object.max_group_size is not None and object.min_group_size is None %}
              <{{ object.max_group_size }}
            {% endif %}
            {% if object.max_group_size is not None and object.min_group_size is not None %}
              {{ object.min_group_size }}-{{ object.max_group_size }}
            {% endif %}
            <br>
          {% endif %}

          {% if object.activity_length %}
            <div class="content-item-tagstitle">{% trans "Duration" %}</div>
            &emsp; {{ object.activity_length }} min <br>
          {% endif %}

          {% if object.staff %}
            <div class="content-item-tagstitle">{% trans "Number of staff" %}</div>
            &emsp; {{ object.staff }} <br>
          {% endif %}

          {% if domains_sans_rri_and_methodologies %}
            {% regroup domains_sans_rri_and_methodologies by type as domains_list %}
            {% for type in domains_list %}
              <div class="content-item-tagstitle">{% trans type.grouper.name %}</div>
              {% for domain in type.list %}
                &emsp;<a class="search-link" href="{% url "content_item:search" domain=domain.slug %}">{% trans domain.name %}</a>
                {% page_block domain.slug language=object.language template="content_item/fragments/content_item_domain_popover.html" %}
                <br>
              {% endfor %}
            {% endfor %}
          {% endif %}

        </div>

        {% if object.tags.all %}
          <div class="col-md-12">
            <hr class="content-item-separator"/>
          </div>
          <div class="col-md-12 content-item-tagstitle">
            {% trans "You might also like" %}
          </div>
          <div class="col-md-12">
            {% for tag in object.tags.all %}
              <a class="search-link" href="{% url "content_item:search"  %}?tags={{ tag }}"> {{ tag }}</a>
              {% if not forloop.last %} <i class="fa fa-circle content-item-dot" aria-hidden="true"></i>
              {% endif %}
            {% endfor %}
          </div>

      {% endif %}

      <a href="{% url "content_item:search" domain=object.main_discipline.slug %}"
            class="btn btn-primary primary-color btn-block mb-3 mt-3">
          {% trans "FIND SIMILAR" %}
        </a>


      {% if evaluation_link %}
        <a href="{{ evaluation_link }}"
        class="btn btn-primary btn-block mb-3">
          {% trans "Evaluate us!" %}
        </a>
      {% endif %}
      </div>
    </div>


  <div class="container content-item-padded-row-top {{ object.main_discipline.slug }}" id="_appendHere">
    {% include "content_item/resource_list.html" %}
  </div>

  {% if can_edit %}
    <div class="container">
      <div class="row">
        <a class="btn btn-primary" href="{% url "content_item:edit" pk=object.pk %}">
          {% trans "Edit" %}
        </a>
        <a class="btn" href="{% url "content_item:add-lang" group_id=object.group.pk %}">
          {% trans "Add another lang version" %}
        </a>
        <a id="content-item-delete" class="btn btn-warning" href="{% url "content_item:delete" pk=object.pk %}">
          {% trans "Delete" %}
        </a>
        <div id="add-resource" class="btn-group">
          <button type="button" class="btn btn-danger dropdown-toggle" data-toggle="dropdown" aria-haspopup="true"
                  aria-expanded="false">
            {% trans "Add a resource" %}
          </button>
          <div class="dropdown-menu">
            {% for type, resource_type in resource_types.items %}
              <a class="dropdown-item"
                 data-type="{{ type }}"
                 href="{% url resource_type.url content_item_id=object.pk %}"
              >
                {{ resource_type.label }}
              </a>
            {% endfor %}
          </div>
        </div>
      </div>
    </div>
  {% endif %}

  {% if DISCOURSE_ROOT_URL %}
    {#  Scripts added to page-scripts block #}

    <div class="container content-item-padded-row-top">
      <div id='discourse-comments'>

      </div>
    </div>
  {% endif %}


{% endblock %}

{% block modal %}
  {% trans "Upload a resource" as modal_title %}
  {% include "fragments/generic-modal.html" with modal_title=modal_title %}
{% endblock %}

www/content_item/templates/content_item/verify_form.html
{% load crispy_forms_tags static %}

<form
  id="resource-form" class="form-horizontal" method="post" action="{% url "content_item:verify" pk=object.id %}"
  accept-charset="UTF-8"
>
  {% csrf_token %}
  {{ form|crispy }}
</form>