config/urls.py
# -*- coding: utf-8 -*-
"""Global routings."""
import pathlib

from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.views import defaults as default_views
from django.views.generic import RedirectView
from django.views.i18n import JavaScriptCatalog
from django.views.static import serve
from rest_framework import routers

from www.filestorage.views import StartFileUpload
from www.landing_page.views import LandingPage
from www.tags.views import TagViewset
from www.translated_page.views import PageCatchallView

from discourse_django_sso.views import SSOProviderView


API_ROUTER = routers.DefaultRouter()

API_ROUTER.register('tag/(?P<content_type_id>\d+)', TagViewset)


api_urls = [
    url(r'fileupload/?$', StartFileUpload.as_view(), name="start-file-upload")
]

api_urls += API_ROUTER.urls

urlpatterns = [
    url(r'^$', RedirectView.as_view(pattern_name='landing-discipline'), name='home'),
    url(r'^discipline/?$', LandingPage.as_view()),
    url(r'^discipline(?:/(?P<discipline>[\w+.\-_]+))?/?$', LandingPage.as_view(), name='landing-discipline'),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^jsi18n/$', JavaScriptCatalog.as_view(), name='javascript-catalog'),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, include(admin.site.urls)),

    # User management
    url(r'^users/', include('www.users.urls', namespace='users')),
    url(r'^accounts/', include('allauth.urls')),

    url('^api/', include(api_urls, namespace="api")),

    url(r'^resource/simulation', include('www.simulation.urls', namespace='simulation')),
    url(r'^resource/', include('www.resource.urls', namespace='resource')),
    url(r'^content_item/', include('www.content_item.urls', namespace='content_item')),
    url(r'^course/', include('www.course.urls', namespace='course')),
    url(
        r'^discourse/sso/?',
        SSOProviderView.as_view(
            sso_redirect=settings.DISCOURSE_SSO_URL,
            sso_secret=settings.DISCOURSE_SSO_SECRET,
        ),
        name='sso'
    ),
    url(
        r'^silf/sso/?',
        SSOProviderView.as_view(
            sso_redirect=settings.SILF_SSO_URL,
            sso_secret=settings.SILF_SSO_SECRET,
        ),
        name='silfsso'
    ),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]

    # This only in debug config as in production config we use js reverse rendered to a static file.
    from django_js_reverse.views import urls_js

    favicon_path = pathlib.Path('compose') / 'nginx' / 'www-data' / 'favicon.ico'
    root = pathlib.Path(__file__).parents[1]
    urlpatterns += [
        url(r'^django_js_reverse/?$', urls_js, name='js_reverse'),
        url(r'^favicon.ico/?$', serve, kwargs={"path": str(favicon_path), 'document_root': root})
    ]


urlpatterns += [
    url('(?P<slug>.*)/?', PageCatchallView.as_view())
]

if settings.ENABLE_TOOLBAR:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

www/course/urls.py
"""Urls for course app."""
# -*- coding: utf-8 -*-

from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        regex=r'(?P<pk>\d+)/edit$',
        view=views.CourseUpdateView.as_view(),
        name='edit'
    ),
    url(
        regex=r'(?P<pk>\d+)/delete$',
        view=views.CourseDeleteView.as_view(),
        name='delete'
    ),
    url(
        regex=r'^(?P<pk>\d+)$',
        view=views.CourseDetailView.as_view(),
        name='detail'
    ),
    url(
        regex=r'^(?P<pk>\d+)/(?P<order>\d+)$',
        view=views.CourseLessonView.as_view(),
        name='lesson'
    ),
    url(
        regex=r'new$',
        view=views.CourseCreateView.as_view(),
        name='new'
    ),
    url(
        regex=r'my$',
        view=views.MyCoursesListView.as_view(),
        name='my-list'
    ),
    url(
        regex=r'item/(?P<pk>\d+)/up',
        view=views.CourseItemUpView.as_view(),
        name="up"
    ),
    url(
        regex=r'item/(?P<pk>\d+)/down',
        view=views.CourseItemDownView.as_view(),
        name="down"
    ),
    url(
        regex=r'item/(?P<pk>\d+)/delete',
        view=views.CourseItemDeleteView.as_view(),
        name="delete"
    ),
    url(
        regex=r'item/(?P<course_id>\d+)/add-item',
        view=views.CourseItemAddView.as_view(),
        name="add_item"
    ),
    url(
        regex=r'$',
        view=views.CourseListView.as_view(),
        name='list'
    ),
]

www/course/models.py
"""Models for course app."""
# -*- coding: utf-8 -*-

from django.conf import settings
from django.db import models
from django.utils.translation import ugettext_lazy
from ordered_model.models import OrderedModel

from ..content_item.models import ContentItem
from ..utils.validators import image_name_validator


class Course(models.Model):
    """Course model"""
    name = models.CharField(
        verbose_name='Course name',
        max_length=128,
        blank=False,
        null=False
    )

    description = models.TextField(
        verbose_name='Course description',
        blank=False,
        null=False
    )

    cover_image = models.ImageField(
        verbose_name='Course cover image',
        blank=True,
        null=True,
        validators=[image_name_validator],
        help_text=ugettext_lazy('Will be cropped to aspect ratio 6.75:1 (or 1080x160px)')
    )

    cover_image_resized = models.ImageField(
        editable=False, blank=True, null=True
    )

    items = models.ManyToManyField(
        ContentItem,
        related_name='courses',
        through='CourseItem',
        verbose_name='Course content'
    )

    owners = models.ManyToManyField(
        to=settings.AUTH_USER_MODEL,
        verbose_name=ugettext_lazy("Owners"),
        help_text=ugettext_lazy("List of users that can edit this course")
    )

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        """Return absolute url to this course"""
        from django.urls import reverse
        return reverse('course:detail', args=[str(self.id)])

    class Meta:
        ordering = ['-created_at']


class CourseItem(OrderedModel):
    """M2M through model for Course and ContentItem"""
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    content_item = models.ForeignKey(ContentItem, on_delete=models.CASCADE)
    updated_at = models.DateTimeField(auto_now=True)
    order_with_respect_to = 'course'

    class Meta(OrderedModel.Meta):
        ordering = ('course', 'order')

    def __str__(self):
        return '{} - {}'.format(
            self.course.__str__(),
            self.content_item.__str__()
        )

    def save(self, **kwargs):  # pylint: disable=arguments-differ
        self.course.updated_at = self.updated_at
        self.course.save()
        super().save(**kwargs)

www/course/forms.py
# -*- coding: utf-8 -*-
"""Forms for course app."""

from django import forms
from django.conf import settings

from www.content_item.models import Domain
from www.course import models, tasks


class CourseForm(forms.ModelForm):
    """Common Course form"""

    def save(self, commit=True):
        instance = super().save(commit)
        tasks.resize_course_images.delay(course_pk=instance.pk)
        return instance

    class Meta:
        """Meta class"""
        model = models.Course
        exclude = ('items', 'owners')


class CourseItemFilterForm(forms.Form):
    """Form used to filter content items to be added to a course."""

    language = forms.ChoiceField(required=False)
    discipline = forms.ModelChoiceField(queryset=Domain.objects.none(), required=False)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['language'].choices = (('', '-' * 7), ) + tuple(settings.LANGUAGES)
        self.fields['discipline'].queryset = Domain.objects.filter(type__slug="discipline")


class CourseItemAddForm(forms.ModelForm):
    """Form for adding Course Items to a course"""

    class Meta:
        """Metaclass"""
        model = models.CourseItem
        fields = [
            'content_item'
        ]

www/course/views.py
"""Views for course app."""
# -*- coding: utf-8 -*-

from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.db.models import Prefetch
from django.http import Http404, HttpResponse
from django.shortcuts import redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import ListView, DetailView, DeleteView, CreateView, \
    UpdateView
from django.views.generic.detail import SingleObjectMixin

from www.course import models
from www.course.models import CourseItem
from . import forms
from .models import Course
from ..content_item.models import ContentItem
from ..content_item.views import get_context_for_resources


class CourseListView(ListView):
    """List view for Courses"""

    model = Course
    context_object_name = 'courses'


class MyCoursesListView(LoginRequiredMixin, ListView):
    """List view for Courses owned by current user"""

    context_object_name = 'courses'

    def get_queryset(self):
        return Course.objects.filter(owners=self.request.user)


class CourseDetailMixin(object):
    """Course detail mixin"""

    model = Course
    context_object_name = 'course'
    queryset = Course.objects.prefetch_related(
        Prefetch(
            'items',
            ContentItem.objects.order_by('courseitem__order')
        )
    )


class CourseDetailView(CourseDetailMixin, DetailView):
    """Course detail view"""

    def get_context_data(self, **kwargs):
        user = self.request.user
        course = self.get_object()
        kwargs['is_owner'] = user.is_authenticated and course.owners.filter(id=user.pk).exists()
        return super().get_context_data(**kwargs)


class CourseLessonView(CourseDetailMixin, DetailView):
    """Course lesson view"""

    template_name = 'course/course_lesson.html'

    def get_context_data(self, **kwargs):
        try:
            number = int(self.kwargs['order'])
            order = number - 1
            course = kwargs['object']
            content = course.items.get(courseitem__order=order)

            kwargs.update(get_context_for_resources(self.request, content))
            kwargs.update({
                'lesson': {
                    'content': content,
                    'number': number,
                    'has_prev': number > 1,
                    'has_next': number < course.items.count()
                }
            })
            return super().get_context_data(**kwargs)
        except ContentItem.DoesNotExist as ex:
            raise Http404('No %s matches the given query.' % ex)


class CourseCreateView(LoginRequiredMixin, CreateView):
    """Create Course view"""
    model = Course
    form_class = forms.CourseForm

    def get_success_url(self):
        return self.object.get_absolute_url()

    def form_valid(self, form):
        result = super().form_valid(form)
        self.object.save()
        self.object.owners.add(self.request.user)
        return result


class CourseOwnerMixin(UserPassesTestMixin):  # pylint: disable=no-member
    """View visible only to owner of course."""
    raise_exception = True
    model = Course

    def test_func(self) -> bool:
        user = self.request.user
        course = self.get_object()
        return user.is_authenticated and course.owners.filter(id=user.pk).exists()


class CourseItemOwnerMixin(UserPassesTestMixin):  # pylint: disable=no-member
    """View visible only to owner of course."""
    raise_exception = True
    model = CourseItem

    def test_func(self) -> bool:
        user = self.request.user
        course = self.get_object().course
        return user.is_authenticated and course.owners.filter(id=user.pk).exists()


class CourseUpdateView(CourseOwnerMixin, UpdateView):
    """Update Course View"""
    form_class = forms.CourseForm

    def get_items_queryset(self):
        """Returns (filtered) queryset of content items that can be added."""
        qs = ContentItem.objects.filter(hidden=False)
        filter_form = forms.CourseItemFilterForm(data=self.request.GET)
        if filter_form.is_valid():
            if filter_form.cleaned_data['language']:
                qs = qs.filter(language=filter_form.cleaned_data['language'])
            if filter_form.cleaned_data['discipline']:
                qs = qs.filter(domains=filter_form.cleaned_data['discipline'])
        return qs

    def get_item_add_from(self):
        """Create to add new items to this course."""
        form = forms.CourseItemAddForm()
        form.fields['content_item'].queryset = self.get_items_queryset()
        return form

    def get_context_data(self, **kwargs):
        kwargs.update({
            "filter_form": forms.CourseItemFilterForm(data=self.request.GET),
            "item_add_form": self.get_item_add_from(),
            "course_items": models.CourseItem.objects.filter(course=self.object).prefetch_related('content_item')
        })
        return super().get_context_data(**kwargs)

    def get_success_url(self):
        return self.object.get_absolute_url()


class CourseItemViewBase(CourseItemOwnerMixin, SingleObjectMixin, View):
    """Base class for views that operate on course items."""

    def perform_action(self, item: CourseItem):
        """Extension point, to perform specific action"""

    def post(self, request, **kwargs):  # pylint: disable=unused-argument
        """POST handler (only handler here)"""
        course_item = self.get_object()
        self.perform_action(course_item)
        if self.request.META.get("HTTP_REFERER"):
            # Preserve filters set via get parameters
            return redirect(self.request.META.get("HTTP_REFERER"))
        return redirect('course:edit', pk=course_item.course_id)


class CourseItemUpView(CourseItemViewBase):
    """Moves course item UP."""

    def perform_action(self, item: CourseItem):
        item.up()


class CourseItemDownView(CourseItemViewBase):
    """Moves course item DOWN."""
    def perform_action(self, item: CourseItem):
        item.down()


class CourseItemDeleteView(CourseItemViewBase):
    """Deletes course item"""
    def perform_action(self, item: CourseItem):
        item.delete()


class CourseItemAddView(UserPassesTestMixin, CreateView):
    """Adds course item."""
    model = CourseItem
    raise_exception = True
    form_class = forms.CourseItemAddForm

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.course = None

    def dispatch(self, request, *args, **kwargs):
        self.course = get_object_or_404(Course, pk=self.kwargs['course_id'])
        return super().dispatch(request, *args, **kwargs)

    def test_func(self):
        user = self.request.user
        course = self.course
        return user.is_authenticated and course.owners.filter(id=user.pk).exists()

    def form_invalid(self, form):  # pragma: no cover
        return HttpResponse(status=400)

    def form_valid(self, form):
        item = form.save(commit=False)
        item.course = self.course
        item.save()
        if self.request.META.get("HTTP_REFERER"):
            # Preserve filters set via get parameters
            return redirect(self.request.META.get("HTTP_REFERER"))
        return redirect('course:edit', pk=item.pk)


class CourseDeleteView(CourseOwnerMixin, DeleteView):
    """Delete Course View"""
    success_url = reverse_lazy('course:list')

www/course/templates/course/course_confirm_delete.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{{ course.name }}{% endblock %}

{% block content %}
<form action="" method="post" class="form">
    {% csrf_token %}
    <p>{% trans "Are you sure you want to delete" %} "{{ object }}"?</p>
    <button type="submit" class="btn btn-danger">{% trans "Confirm" %}</button>
</form>
{% endblock content %}

www/course/templates/course/course_detail.html
{% extends "base.html" %}
{% load static i18n %}

{% block title %}{{ course.name }}{% endblock %}

{% block content %}
<div class="container-fluid">
    {% if course.cover_image_resized %}
    <img class="cover-image" src="{{ course.cover_image_resized.url }}" alt="{{ course.name }}">
    {% endif %}
</div>

<div class="container">
    <div class="jumbotron">
        {% if is_owner %}
        <div class="row justify-content-end">
            <div class="col-1">
                <a href="{% url "course:edit" course.pk %}" type="button" class="btn btn-primary btn-sm">{% trans "Edit" %}</a>
            </div>
            <div class="col-1">
                <a href="{% url "course:delete" course.pk %}" type="button" class="btn btn-danger btn-sm">{% trans "Delete" %}</a>
            </div>
        </div>
        {% endif %}
        <h1 class="display-3">{{ course.name }}</h1>
        <div class="lead">
            {{ course.description }}
        </div>
        <div class="small mt-3">
            <p>{% trans "Created at" %} {{ course.created_at }}</p>
            <p>{% trans "Last modified at" %} {{ course.updated_at }}</p>
        </div>
    </div>

    <div>
        {% for item in course.items.all %}
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">
                    <a href="{% url 'course:lesson' course.id forloop.counter %}">{{ item.title }}</a>
                </h5>
                <p class="card-text">{{ item.description }}</p>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock content %}

www/course/templates/course/course_form.html
{% extends "base.html" %}
{% load bootstrap3 i18n static formset_tags %}

{% block title %}{{ course.name }}{% endblock %}

{% block content %}
  <div id="items" class="container">
    <h1>{% trans "Course metadata" %}</h1>
    <form action="" method="post" class="form" enctype="multipart/form-data">{% csrf_token %}
      {% bootstrap_form form %}
      <button class="btn btn-primary">{% trans "Submit" %}</button>
    </form>
  </div>

  {% if filter_form %}

  <h1>{% trans "Course content" %}</h1>
  <div class="container">
    <table id="items" class="table table-bordered">
      <thead>
      <tr>
        <td>{% trans "Index" %}</td>
        <td>{% trans "Content Item Name" %}</td>
        <td>{% trans "Content Item Language" %}</td>
        <td>{% trans "Operations" %}</td>
      </tr>
      </thead>
      <tbody>
      {% for item in course_items %}
        <tr>
          <td>{{ forloop.counter }}</td>
          <td>{{ item.content_item.title }}</td>
          <td>{{ item.content_item.language }}</td>
          <td>
            <form method="post" action="{% url "course:down" pk=item.pk%}">
              {% csrf_token %}
              <button class="btn btn-sm btn-default">
                <i aria-hidden class="fa fa-arrow-down"></i> <span class="sr-only">{% trans "Move down" %}</span>
              </button>
            </form>
            <form method="post" action="{% url "course:up" pk=item.pk%}">
              {% csrf_token %}
              <button class="btn btn-sm btn-default">
                <i aria-hidden class="fa fa-arrow-up"></i> <span class="sr-only">{% trans "Move up" %}</span>
              </button>
            </form>
            <form method="post" action="{% url "course:delete" pk=item.pk%}">
              {% csrf_token %}
              <button class="btn btn-sm btn-danger"><i aria-hidden class="fa fa-times-circle"></i> <span class="sr-only">{% trans "Delete" %}</span>
              </button>
            </form>
          </td>
        </tr>
      {% empty %}
        <tr>
          <td colspan="4">{% trans "Course items will be here once you add some!" %}</td>
        </tr>
      {% endfor %}
      </tbody>
    </table>
  </div>

  <h2>{% trans "Add new content" %}</h2>
  <h4>{% trans "Filter content items" %}</h4>

  <form method="get" class="form-inline" id="filter-form">
    {#  <label class="sr-only" for="language-input">Language</label>#}
    {#  <select name="language" id="language-input" class="form-control">#}
    {#    <option value="">{% trans "Select language here to filter" %}</option>#}
    {#    {% for language in LANGUAGES %}#}
    {#      <option value="{{ language.0 }}">{{ language.1 }}</option>#}
    {#    {% endfor %}#}
    {#  </select>#}
    {#  <label class="sr-only" for="discipline-input">Discipline</label>#}
    {#  <select name="discipline" id="discipline-input" class="form-control ml-4">#}
    {#    <option value="">{% trans "Select discipline here to filter" %}</option>#}
    {#    {% for discipline in disciplines %}#}
    {#      <option value="{{ discipline.slug }}">{% trans discipline.name %}</option>#}
    {#    {% endfor %}#}
    {#  </select>#}

    {% bootstrap_form filter_form layout=inline %}

    <button class="btn btn-default">{% trans "Apply filters" %}</button>

  </form>

  <h4>{% trans "Add new materials" %}</h4>

  <form method="post" class="form" action="{% url "course:add_item" course_id=object.pk %}" id="add-form">
    {% csrf_token %}
    {% bootstrap_form item_add_form layout="inline" %}
    <button class="btn btn-primary">{% trans "Add new material" %}</button>
  </form>

  {% endif %}

{% endblock content %}

{% block page-css %}
  <style>
    h4{
      margin-top: .7em;
    }
    #filter-form .control-label{
      margin-left: 1em;
      margin-right: .3em;
    }
    #filter-form button{
      margin-left: 1em;
    }
    #add-form .control-label{
      margin-left: 1em;
      margin-right: .3em;
    }
    #add-form [for=id_content_item]{
      display: none
    }
    #items .btn-sm {
      margin-left: .3em;
      margin-right: .3em;
    }
    #items form {
      display: inline;
    }
  </style>
{% endblock %}

{% block page_js %}
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" integrity="sha384-RdQbeSCGSeSdSlTMGnUr2oDJZzOuGjJAkQy1MbKMu8fZT5G0qlBajY0n0sY/hKMK" crossorigin="anonymous"/>
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js" integrity="sha384-uQwKPrmNkEOvI7rrNdCSs6oS1F3GvnZkmPtkntOSIiPQN4CCbFSxv+Bj6qe0mWDb" crossorigin="anonymous"></script>
<script>
  $("#id_content_item").select2()
</script>
{% endblock %}

www/course/templates/course/course_lesson.html
{% extends "base.html" %}
{% load bootstrap3 i18n static %}

{% block title %}{{ course.name }}::{{ lesson.number }} – {{ lesson.content.title }}{% endblock %}

{% block content %}
<div class="container-fluid">
    {% if course.cover_image %}
    <img class="cover-image" src="{{ course.cover_image.url }}" alt="{{ course.name }}">
    {% endif %}
</div>

<div class="container mt-3 pt-3 {{ lesson.content.main_discipline.slug }}">
    <div class="row">
        <div class="col-sm-3">
            <div class="card">
                <div class="card-header">
                    <h5><a href="{% url 'course:detail' course.id %}">
                        {% trans "Course outline" %}
                    </a></h5>
                </div>
                <div class="list-group list-group-flush">
                {% for item in course.items.all %}
                    <a href="{% url 'course:lesson' course.id forloop.counter %}"
                    class="list-group-item list-group-item-action {% if forloop.counter == lesson.number %}active{% endif %}">
                        {{ item.title }}
                    </a>
                {% endfor %}
                </div>
            </div>
        </div>
        <div class="col-sm-9">
            <div class="row">
                <div class="col content-item-title">
                    <h2 class="discourse-embed">{{ lesson.content.title }}</h2>
                </div>
            </div>
            <div class="row">
                <div class="col content-item-authors">
                    <strong>{% trans "Authors" %}:</strong> {% for author in lesson.content.authors %} {{ author }}{% if not forloop.last %},{% endif %} {{ endif }}{% endfor %}
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <hr class="content-item-titleseparator" />
                </div>
            </div>
            {% if lesson.content.description %}
            <div class="row">
                <div class="col content-item-description discourse-embed">
                    <a data-toggle="collapse" href="#content-description" aria-expanded="false" aria-controls="content-description">
                        {% trans "Description" %}
                    </a>
                    <div id="content-description" class="collapse">
                    {{ lesson.content.description }}
                    </div>
                </div>
            </div>
            {% endif %}
            {% if default_resource %}
            <div class="container content-item-padded-row-top {{ lesson.content.field }}">
                <div class="content-item-resource-list" id="resourceList">
                {% with default_resource as resource_manager  %}
                {% with default_resource.resource as resource_obj  %}
                    <div class="resource-tile">
                    {% include default_resource.template_name %}
                    </div>
                {% endwith %}
                {% endwith %}
                </div>
            </div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock content %}

{% block footer %}
<div class="container mb-3">
    <div class="row">
        <div class="col offset-sm-3">
            {% if lesson.has_prev %}
            <a href="{% url 'course:lesson' course.id lesson.number|add:"-1" %}" class="btn btn-primary">
                <i class="fa fa-chevron-left" aria-hidden="true"></i>
            </a>
            {% endif %}
        </div>
        <div class="col text-right">
            {% if lesson.has_next %}
            <a href="{% url 'course:lesson' course.id lesson.number|add:"1" %}" class="btn btn-primary">
                <i class="fa fa-chevron-right" aria-hidden="true"></i>
            </a>
            {% endif %}
        </div>
    </div>
</div>
{% endblock footer %}

www/course/templates/course/course_list.html
{% extends "base.html" %}
{% load static i18n %}

{% block title %}{% trans "Course List" %}{% endblock %}

{% block content %}

<div class="container">
    <h2>{% trans "Courses" %}</h2>

    {% if courses %}
    <div class="card-columns">
        {% for course in courses %}
        <div class="card">
            {% if course.cover_image %}
            <img class="card-img-top img-fluid" src="{{ course.cover_image.url }}" alt="{{ course.name }}">
            {% endif %}
            <div class="card-body">
                <h4 class="card-title">{{ course.name }}</h4>
                <p class="card-text">{{ course.description }}</p>
                <a href="{% url 'course:detail' course.id %}" class="card-link">{% trans "Go to course" %}</a>
            </div>
            <div class="card-footer text-muted">
                <p class="small">{% trans "Last modified at" %} {{ course.updated_at }}</p>
            </div>
        </div>
        {% endfor %}
    </div>
    {% else %}
        <p>{% trans "No course available at the moment." %}</p>
    {% endif %}
</div>

{% endblock content %}